# Generated by Django 2.1.4 on 2019-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng_lat', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('img_url', models.URLField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('uid', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='detailInfo',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('detail_url', models.URLField(blank=True)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('distance', models.CharField(max_length=20)),
                ('overall_rating', models.CharField(blank=True, max_length=10)),
                ('service_rating', models.CharField(blank=True, max_length=10)),
                ('hygiene_rating', models.CharField(blank=True, max_length=10)),
                ('facility_rating', models.CharField(blank=True, max_length=10)),
                ('hotel_facility', models.CharField(blank=True, max_length=300)),
                ('hotel_service', models.CharField(blank=True, max_length=300)),
                ('inner_facility', models.CharField(blank=True, max_length=400)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
