# Generated by Django 2.1.4 on 2019-03-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinfo',
            name='distance',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
